//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""BaseDriving"",
            ""id"": ""f54d0cd6-3c69-4827-a619-772884abda79"",
            ""actions"": [
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""7a57967c-16b5-46ae-b206-1947024150cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""91136f86-2d01-4d8b-a95b-2fd3ca873835"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""776e900d-7bbd-4769-8d2d-f40720270dae"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BaseDriving
        m_BaseDriving = asset.FindActionMap("BaseDriving", throwIfNotFound: true);
        m_BaseDriving_Boost = m_BaseDriving.FindAction("Boost", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BaseDriving
    private readonly InputActionMap m_BaseDriving;
    private List<IBaseDrivingActions> m_BaseDrivingActionsCallbackInterfaces = new List<IBaseDrivingActions>();
    private readonly InputAction m_BaseDriving_Boost;
    public struct BaseDrivingActions
    {
        private @PlayerControls m_Wrapper;
        public BaseDrivingActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Boost => m_Wrapper.m_BaseDriving_Boost;
        public InputActionMap Get() { return m_Wrapper.m_BaseDriving; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BaseDrivingActions set) { return set.Get(); }
        public void AddCallbacks(IBaseDrivingActions instance)
        {
            if (instance == null || m_Wrapper.m_BaseDrivingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BaseDrivingActionsCallbackInterfaces.Add(instance);
            @Boost.started += instance.OnBoost;
            @Boost.performed += instance.OnBoost;
            @Boost.canceled += instance.OnBoost;
        }

        private void UnregisterCallbacks(IBaseDrivingActions instance)
        {
            @Boost.started -= instance.OnBoost;
            @Boost.performed -= instance.OnBoost;
            @Boost.canceled -= instance.OnBoost;
        }

        public void RemoveCallbacks(IBaseDrivingActions instance)
        {
            if (m_Wrapper.m_BaseDrivingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBaseDrivingActions instance)
        {
            foreach (var item in m_Wrapper.m_BaseDrivingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BaseDrivingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BaseDrivingActions @BaseDriving => new BaseDrivingActions(this);
    public interface IBaseDrivingActions
    {
        void OnBoost(InputAction.CallbackContext context);
    }
}
